# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# ElementwiseOp[kind] and the native backend's SIMD math.

import extensibility
from extensibility import ElementwiseUnaryMixedOp

from .elementwise import ElementwiseOp


@extensibility.register("elementwise_abs")
struct ElementwiseAbs(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["abs"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_acos")
struct ElementwiseAcos(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["acos"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_acosh")
struct ElementwiseAcosh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["acosh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_airy_ai")
struct ElementwiseAiryAi(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["airy_ai"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_angle")
struct ElementwiseAngle(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["angle"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_asin")
struct ElementwiseAsin(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["asin"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_asinh")
struct ElementwiseAsinh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["asinh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_atan")
struct ElementwiseAtan(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["atan"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_atanh")
struct ElementwiseAtanh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["atanh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_bessel_j0")
struct ElementwiseBesselJ0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["bessel_j0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_bessel_j1")
struct ElementwiseBesselJ1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["bessel_j1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_bessel_y0")
struct ElementwiseBesselY0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["bessel_y0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_bessel_y1")
struct ElementwiseBesselY1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["bessel_y1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_ceil")
struct ElementwiseCeil(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["ceil"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_cos")
struct ElementwiseCos(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["cos"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_cosh")
struct ElementwiseCosh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["cosh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_digamma")
struct ElementwiseDigamma(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["digamma"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_entr")
struct ElementwiseEntr(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["entr"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erf")
struct ElementwiseErf(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erf"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erfc")
struct ElementwiseErfc(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erfc"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erfcx")
struct ElementwiseErfcx(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erfcx"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erfinv")
struct ElementwiseErfinv(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erfinv"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_exp")
struct ElementwiseExp(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["exp"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_exp2")
struct ElementwiseExp2(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["exp2"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_expm1")
struct ElementwiseExpm1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["expm1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_floor")
struct ElementwiseFloor(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["floor"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_frac")
struct ElementwiseFrac(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["frac"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_gelu_none")
struct ElementwiseGeluNone(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["gelu_none"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_gelu_tanh")
struct ElementwiseGeluTanh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["gelu_tanh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_i0")
struct ElementwiseI0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["i0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_i0e")
struct ElementwiseI0e(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["i0e"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_i1")
struct ElementwiseI1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["i1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_i1e")
struct ElementwiseI1e(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["i1e"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_isinf")
struct ElementwiseIsinf(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["isinf"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_isnan")
struct ElementwiseIsnan(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["isnan"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_lgamma")
struct ElementwiseLgamma(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["lgamma"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log10")
struct ElementwiseLog10(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log10"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log_ndtr")
struct ElementwiseLogNdtr(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log_ndtr"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_logical_not")
struct ElementwiseLogicalNot(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["logical_not"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log")
struct ElementwiseLog(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log1p")
struct ElementwiseLog1p(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log1p"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log2")
struct ElementwiseLog2(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log2"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_logit")
struct ElementwiseLogit(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["logit"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_modified_bessel_i0")
struct ElementwiseModifiedBesselI0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["modified_bessel_i0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_modified_bessel_i1")
struct ElementwiseModifiedBesselI1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["modified_bessel_i1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_modified_bessel_k0")
struct ElementwiseModifiedBesselK0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["modified_bessel_k0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_modified_bessel_k1")
struct ElementwiseModifiedBesselK1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["modified_bessel_k1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_ndtri")
struct ElementwiseNdtri(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["ndtri"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_neg")
struct ElementwiseNeg(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["neg"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_reciprocal")
struct ElementwiseReciprocal(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["reciprocal"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_relu")
struct ElementwiseRelu(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["relu"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_round")
struct ElementwiseRound(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["round"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_rsqrt")
struct ElementwiseRsqrt(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["rsqrt"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_scaled_modified_bessel_k0")
struct ElementwiseScaledModifiedBesselK0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["scaled_modified_bessel_k0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_scaled_modified_bessel_k1")
struct ElementwiseScaledModifiedBesselK1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["scaled_modified_bessel_k1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sigmoid")
struct ElementwiseSigmoid(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sigmoid"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sign")
struct ElementwiseSign(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sign"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_signbit")
struct ElementwiseSignbit(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["signbit"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_silu")
struct ElementwiseSilu(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["silu"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sin")
struct ElementwiseSin(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sin"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sinc")
struct ElementwiseSinc(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sinc"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sinh")
struct ElementwiseSinh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sinh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_spherical_bessel_j0")
struct ElementwiseSphericalBesselJ0(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["spherical_bessel_j0"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sqrt")
struct ElementwiseSqrt(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sqrt"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_tan")
struct ElementwiseTan(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["tan"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_tanh")
struct ElementwiseTanh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["tanh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_trigamma")
struct ElementwiseTrigamma(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["trigamma"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_trunc")
struct ElementwiseTrunc(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["trunc"]
        return Op.elementwise[dtype, out_dtype, width](x)
