# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# ElementwiseOp[kind] and the native backend's SIMD math.

import extensibility
from extensibility import ElementwiseUnaryMixedOp

from .elementwise import ElementwiseOp


@extensibility.register("elementwise_abs")
struct ElementwiseAbs(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["abs"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_acos")
struct ElementwiseAcos(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["acos"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_acosh")
struct ElementwiseAcosh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["acosh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_angle")
struct ElementwiseAngle(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["angle"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_asin")
struct ElementwiseAsin(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["asin"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_asinh")
struct ElementwiseAsinh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["asinh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_atan")
struct ElementwiseAtan(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["atan"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_atanh")
struct ElementwiseAtanh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["atanh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_ceil")
struct ElementwiseCeil(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["ceil"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_cos")
struct ElementwiseCos(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["cos"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_cosh")
struct ElementwiseCosh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["cosh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erf")
struct ElementwiseErf(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erf"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erfc")
struct ElementwiseErfc(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erfc"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_erfinv")
struct ElementwiseErfinv(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["erfinv"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_exp")
struct ElementwiseExp(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["exp"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_exp2")
struct ElementwiseExp2(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["exp2"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_expm1")
struct ElementwiseExpm1(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["expm1"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_floor")
struct ElementwiseFloor(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["floor"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_gelu_none")
struct ElementwiseGeluNone(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["gelu_none"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_gelu_tanh")
struct ElementwiseGeluTanh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["gelu_tanh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_isinf")
struct ElementwiseIsinf(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["isinf"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_isnan")
struct ElementwiseIsnan(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["isnan"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_logical_not")
struct ElementwiseLogicalNot(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["logical_not"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log")
struct ElementwiseLog(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log10")
struct ElementwiseLog10(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log10"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log1p")
struct ElementwiseLog1p(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log1p"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_log2")
struct ElementwiseLog2(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["log2"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_neg")
struct ElementwiseNeg(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["neg"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_reciprocal")
struct ElementwiseReciprocal(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["reciprocal"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_relu")
struct ElementwiseRelu(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["relu"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_rsqrt")
struct ElementwiseRsqrt(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["rsqrt"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sigmoid")
struct ElementwiseSigmoid(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sigmoid"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sign")
struct ElementwiseSign(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sign"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_signbit")
struct ElementwiseSignbit(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["signbit"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_silu")
struct ElementwiseSilu(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["silu"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sin")
struct ElementwiseSin(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sin"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sinc")
struct ElementwiseSinc(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sinc"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sinh")
struct ElementwiseSinh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sinh"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_sqrt")
struct ElementwiseSqrt(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["sqrt"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_tan")
struct ElementwiseTan(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["tan"]
        return Op.elementwise[dtype, out_dtype, width](x)


@extensibility.register("elementwise_tanh")
struct ElementwiseTanh(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["tanh"]
        return Op.elementwise[dtype, out_dtype, width](x)
