# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# the native backend's pointwise SIMD math (tmb.kernels.common.pointwise_math).

import extensibility
from extensibility import ElementwiseBinaryOp

from tmb.kernels.common.pointwise_math import param_dtype, pointwise


@extensibility.register("pointwise_atan2")
struct PointwiseAtan2(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["atan2", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_copysign")
struct PointwiseCopysign(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["copysign", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_fmax")
struct PointwiseFmax(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["fmax", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_fmin")
struct PointwiseFmin(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["fmin", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_fmod")
struct PointwiseFmod(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["fmod", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_heaviside")
struct PointwiseHeaviside(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["heaviside", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_hypot")
struct PointwiseHypot(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["hypot", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_nextafter")
struct PointwiseNextafter(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["nextafter", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )
