# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# the native backend's pointwise SIMD math (tmb.kernels.common.pointwise_math).

import extensibility
from extensibility import ElementwiseBinaryOp

from tmb.kernels.common.pointwise_math import param_dtype, pointwise


@extensibility.register("pointwise_atan2")
struct PointwiseAtan2(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["atan2", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_chebyshev_polynomial_t")
struct PointwiseChebyshevPolynomialT(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["chebyshev_polynomial_t", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_chebyshev_polynomial_u")
struct PointwiseChebyshevPolynomialU(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["chebyshev_polynomial_u", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_chebyshev_polynomial_v")
struct PointwiseChebyshevPolynomialV(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["chebyshev_polynomial_v", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_chebyshev_polynomial_w")
struct PointwiseChebyshevPolynomialW(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["chebyshev_polynomial_w", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_copysign")
struct PointwiseCopysign(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["copysign", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_fmax")
struct PointwiseFmax(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["fmax", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_fmin")
struct PointwiseFmin(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["fmin", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_fmod")
struct PointwiseFmod(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["fmod", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_gcd")
struct PointwiseGcd(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["gcd", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_heaviside")
struct PointwiseHeaviside(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["heaviside", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_hermite_polynomial_h")
struct PointwiseHermitePolynomialH(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["hermite_polynomial_h", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_hermite_polynomial_he")
struct PointwiseHermitePolynomialHe(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["hermite_polynomial_he", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_hypot")
struct PointwiseHypot(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["hypot", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_igamma")
struct PointwiseIgamma(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["igamma", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_igammac")
struct PointwiseIgammac(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["igammac", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_laguerre_polynomial_l")
struct PointwiseLaguerrePolynomialL(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["laguerre_polynomial_l", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_lcm")
struct PointwiseLcm(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["lcm", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_ldexp")
struct PointwiseLdexp(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["ldexp", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_legendre_polynomial_p")
struct PointwiseLegendrePolynomialP(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["legendre_polynomial_p", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_logaddexp")
struct PointwiseLogaddexp(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["logaddexp", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_logaddexp2")
struct PointwiseLogaddexp2(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["logaddexp2", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_lshift")
struct PointwiseLshift(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["lshift", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_nextafter")
struct PointwiseNextafter(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["nextafter", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_rshift")
struct PointwiseRshift(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["rshift", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_shifted_chebyshev_polynomial_t")
struct PointwiseShiftedChebyshevPolynomialT(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["shifted_chebyshev_polynomial_t", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_shifted_chebyshev_polynomial_u")
struct PointwiseShiftedChebyshevPolynomialU(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["shifted_chebyshev_polynomial_u", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_shifted_chebyshev_polynomial_v")
struct PointwiseShiftedChebyshevPolynomialV(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["shifted_chebyshev_polynomial_v", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_shifted_chebyshev_polynomial_w")
struct PointwiseShiftedChebyshevPolynomialW(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["shifted_chebyshev_polynomial_w", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_xlog1py")
struct PointwiseXlog1py(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["xlog1py", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_xlogy")
struct PointwiseXlogy(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["xlogy", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )


@extensibility.register("pointwise_zeta")
struct PointwiseZeta(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["zeta", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )
