"""ATen ops: pairwise distances (see agents_docs/native_backend.md).

`_cdist_forward`, `_cdist_backward`, `_pdist_forward`, `_pdist_backward`:
the host side of aten/src/ATen/native/Distance.cpp at v2.14.0 (`cdist_impl`'s
checks, batch broadcasting, empty-input results and its matrix-multiply route
for p = 2, which runs ATen's own `_euclidean_dist` composite through the
dispatcher and so this backend's matmul), with the kernels of
aten/src/ATen/native/cuda/DistanceKernel.cu in the `distance` family. CUDA's
kernels dispatch float and double only, so do these: a half input raises
CUDA's "not implemented for" error where CUDA's kernel would.

`cdist` and `pdist` themselves are CompositeImplicit and reach these through
the dispatcher; the autogenerated `.out` overloads are ATen's composite (functional op,
`resize_output`, `copy_`) rebuilt here (`store_autogen_out`), since the
composite's `resize_` has no kernel on this device.
"""
from std.utils import IndexList
from std.utils.numerics import isinf

from tmb.backend.abi import (
    Owned,
    T,
    TAG_INT_LIST,
    Value,
    Values,
    new_tensor,
    own,
    retain,
    ret_owned,
    ret_ref,
    unsupported,
    v_f64,
    v_int,
    v_is_none,
    v_tensor,
    view_strided,
)
from tmb.backend.device import ctx_for, ctx_ptr, dev
from tmb.backend.kernel_call import KernelCall
from tmb.kernels.common.op_utils import MAX_RANK
from tmb.ops.common import (
    assert_no_internal_overlap,
    cast_to,
    copy_strided_into,
    device_str,
    fill_value,
    resize_out,
)
from tmb.ops.composed import _dispatch, _tensor_value
from tmb.ops.data_movement import _scalar_type_name
from tmb.backend.registry import Site, impl

# The `dists<scalar_t>` member a launch runs (kernels/distance/entry.mojo).
comptime _NORM_ZERO = 0
comptime _NORM_ONE = 1
comptime _NORM_TWO = 2
comptime _NORM_INF = 3
comptime _NORM_P = 4
comptime _NORM_LT_TWO = 5


def _fwd_norm(p: Float64) -> Int:
    """cdist_kernel_impl / pdist_forward_kernel_impl's ladder."""
    if p == 0:
        return _NORM_ZERO
    if p == 1:
        return _NORM_ONE
    if p == 2:
        return _NORM_TWO
    if isinf(p):
        return _NORM_INF
    return _NORM_P


def _bwd_norm(p: Float64) -> Int:
    """The backward ladder: one, lt_two (p < 2), two, inf, general p (p = 0
    never launches)."""
    if p == 1:
        return _NORM_ONE
    if p < 2:
        return _NORM_LT_TWO
    if p == 2:
        return _NORM_TWO
    if isinf(p):
        return _NORM_INF
    return _NORM_P


def _device_type_name(t: T) -> String:
    """`c10::DeviceType` as `operator<<` prints it."""
    if t.on_mojo():
        return "MOJO"
    if t.on_cpu():
        return "CPU"
    return String("device type ", t.device_type)


def _kernel_dtype(t: T, what: StaticString) raises:
    """AT_DISPATCH_FLOATING_TYPES(<what>): float and double, the latter not
    on Apple GPUs."""
    if t.dtype != DType.float32 and t.dtype != DType.float64:
        raise Error(
            '"',
            what,
            "\" not implemented for '",
            _scalar_type_name(t.dtype),
            "'",
        )
    if t.dtype == DType.float64 and dev(t.device)[].api == "metal":
        unsupported(String(what, ": float64 is unavailable on Apple GPUs"))


def _same_dtype(t: T, like: T) raises:
    """`const_data_ptr<scalar_t>()` on an operand of another dtype."""
    if t.dtype != like.dtype:
        raise Error(
            "expected scalar type ",
            _scalar_type_name(like.dtype),
            " but found ",
            _scalar_type_name(t.dtype),
        )


def _on_one_device(a: T, b: T) raises:
    if not a.on_mojo() or not b.on_mojo():
        raise Error(
            "X1 and X2 must have the same device type. X1: ",
            _device_type_name(a),
            " X2: ",
            _device_type_name(b),
        )
    if a.device != b.device:
        raise Error(
            "device of X1 (",
            a.device,
            ") must match device of X2 (",
            b.device,
            ")",
        )


def _batch_shape(x1: T, x2: T) raises -> List[Int]:
    """`infer_size` over the leading (batch) dims of x1 and x2."""
    var n1 = x1.rank - 2
    var n2 = x2.rank - 2
    var nb = max(n1, n2)
    var out = List[Int](capacity=nb)
    for i in range(nb):
        var off = nb - 1 - i
        var d1 = n1 - 1 - off
        var d2 = n2 - 1 - off
        var s1 = x1.dim(d1) if d1 >= 0 else 1
        var s2 = x2.dim(d2) if d2 >= 0 else 1
        if s1 != s2 and s1 != 1 and s2 != 1:
            raise Error(
                "The size of tensor a (",
                s1,
                ") must match the size of tensor b (",
                s2,
                ") at non-singleton dimension ",
                i,
            )
        out.append(s2 if s1 == 1 else s1)
    return out^


def _product(xs: List[Int]) -> Int:
    var p = 1
    for x in xs:
        p *= x
    return p


def _shape_of(batch: List[Int], a: Int, b: Int) -> IndexList[MAX_RANK]:
    """`batch + [a, b]`, right-aligned in the TensorSpec convention."""
    var rank = len(batch) + 2
    var shape = IndexList[MAX_RANK](1)
    var pad = MAX_RANK - rank
    for i in range(len(batch)):
        shape[pad + i] = batch[i]
    shape[MAX_RANK - 2] = a
    shape[MAX_RANK - 1] = b
    return shape


def _expanded_dense(x: T, batch: List[Int]) raises -> Owned:
    """`x.expand(batch + [r, c]).contiguous()`: x itself (a second handle)
    when it already is that tensor."""
    var nb = len(batch)
    var rank = nb + 2
    var shape = _shape_of(batch, x.dim(-2), x.dim(-1))
    var strides = IndexList[MAX_RANK](0)
    var same = x.rank == rank
    var xb = x.rank - 2
    for t in range(rank):
        var p = MAX_RANK - rank + t
        var xd = t - (rank - x.rank)
        if xd < 0:
            strides[p] = 0
            continue
        var xs = x.dim(xd)
        if xs != shape[p]:
            same = False
        strides[p] = 0 if (xs == 1 and shape[p] != 1 and xd < xb) else x.stride(
            xd
        )
    if same and x.contig:
        return own(T(retain(x)))
    var view = own(view_strided(x, shape, strides, rank, x.offset))
    var out = own(new_tensor(shape, rank, x.stype, x.device))
    copy_strided_into(out.t, view.t)
    _ = view^
    return out^


def _dense(x: T) raises -> Owned:
    """`x.contiguous()` as a handle of our own."""
    if x.contig:
        return own(T(retain(x)))
    var out = own(new_tensor(x.shape, x.rank, x.stype, x.device))
    copy_strided_into(out.t, x)
    return out^


def _int_list(shape: IndexList[MAX_RANK], rank: Int) -> List[Int64]:
    var out = List[Int64](capacity=rank)
    for i in range(rank):
        out.append(Int64(shape[MAX_RANK - rank + i]))
    return out^


# aten::_cdist_forward(Tensor x1, Tensor x2, float p, int? compute_mode) -> Tensor
def _cdist_forward(args: Values) raises -> Owned:
    var x1 = v_tensor(args[unsafe_offset=0])
    var x2 = v_tensor(args[unsafe_offset=1])
    var p = v_f64(args[unsafe_offset=2])
    var mode = 0
    if not v_is_none(args[unsafe_offset=3]):
        mode = v_int(args[unsafe_offset=3])
    # _cdist_forward's checks, then cdist_impl's.
    if x1.rank < 2:
        raise Error(
            "cdist only supports at least 2D tensors, X1 got: ", x1.rank, "D"
        )
    if x2.rank < 2:
        raise Error(
            "cdist only supports at least 2D tensors, X2 got: ", x2.rank, "D"
        )
    var c1 = x1.dim(-1)
    if c1 != x2.dim(-1):
        raise Error(
            "X1 and X2 must have the same number of columns. X1: ",
            c1,
            " X2: ",
            x2.dim(-1),
        )
    if not x1.dtype.is_floating_point():
        raise Error(
            "cdist only supports floating-point dtypes, X1 got: ",
            _scalar_type_name(x1.dtype),
        )
    if not x2.dtype.is_floating_point():
        raise Error(
            "cdist only supports floating-point dtypes, X2 got: ",
            _scalar_type_name(x2.dtype),
        )
    if not (p >= 0):
        raise Error("cdist only supports non-negative p values")
    _on_one_device(x1, x2)
    if mode < 0 or mode > 2:
        raise Error("possible modes: 0, 1, 2, but was: ", mode)
    var r1 = x1.dim(-2)
    var r2 = x2.dim(-2)
    var batch = _batch_shape(x1, x2)
    var product = _product(batch)
    var out_rank = len(batch) + 2
    var out_shape = _shape_of(batch, r1, r2)
    if r1 == 0 or r2 == 0 or product == 0:
        var empty = own(new_tensor(out_shape, out_rank, x1.stype, x1.device))
        return empty^
    if c1 == 0:
        var zeros = own(new_tensor(out_shape, out_rank, x1.stype, x1.device))
        fill_value(zeros.t, 0.0)
        return zeros^
    if p == 2 and (mode == 1 or (mode == 0 and (r1 > 25 or r2 > 25))):
        # The matrix-multiply route: ATen's `_euclidean_dist` composite.
        var dist: Owned
        if product == 1:
            dist = own(
                _dispatch(
                    "aten::_euclidean_dist",
                    "",
                    [_tensor_value(x1), _tensor_value(x2)],
                )
            )
        else:
            var e1 = _expanded_dense(x1, [product])
            var e2 = _expanded_dense(x2, [product])
            dist = own(
                _dispatch(
                    "aten::_euclidean_dist",
                    "",
                    [_tensor_value(e1.t), _tensor_value(e2.t)],
                )
            )
            _ = e1^
            _ = e2^
        var dims = _int_list(out_shape, out_rank)
        var shaped = own(
            _dispatch(
                "aten::view",
                "",
                [
                    _tensor_value(dist.t),
                    Value(
                        TAG_INT_LIST,
                        Int32(len(dims)),
                        Int64(Int(dims.unsafe_ptr())),
                        0,
                    ),
                ],
            )
        )
        _ = dims^
        _ = dist^
        return shaped^
    _kernel_dtype(x1, "cdist_cuda")
    _same_dtype(x2, x1)
    var e1 = _expanded_dense(x1, batch)
    var e2 = _expanded_dense(x2, batch)
    var out = own(new_tensor(out_shape, out_rank, x1.stype, x1.device))
    var ctx = ctx_for(x1.device)
    var call = KernelCall("distance", "CdistForward")
    call.arg_dtype(0, x1.dtype)
    call.int(out.t.ptr)
    call.int(e1.t.ptr)
    call.int(e2.t.ptr)
    call.f64(p)
    call.int(_fwd_norm(p))
    call.int(out.t.numel)
    call.int(r1)
    call.int(r2)
    call.int(c1)
    call.int(ctx_ptr(ctx))
    call.run()
    _ = ctx
    _ = e1^
    _ = e2^
    return out^


# aten::_cdist_backward(Tensor grad, Tensor x1, Tensor x2, float p, Tensor cdist) -> Tensor
def _cdist_backward(args: Values) raises -> Owned:
    var grad = v_tensor(args[unsafe_offset=0])
    var x1 = v_tensor(args[unsafe_offset=1])
    var x2 = v_tensor(args[unsafe_offset=2])
    var p = v_f64(args[unsafe_offset=3])
    var dist = v_tensor(args[unsafe_offset=4])
    if x1.rank < 2 or x2.rank < 2:
        raise Error("_cdist_backward: x1 and x2 must be at least 2-D")
    var c1 = x1.dim(-1)
    var r1 = x1.dim(-2)
    var r2 = x2.dim(-2)
    var batch = _batch_shape(x1, x2)
    var product = _product(batch)
    if r1 == 0 or r2 == 0 or c1 == 0 or product == 0:
        # zeros_like(x1)
        var zeros = own(new_tensor(x1.shape, x1.rank, x1.stype, x1.device))
        fill_value(zeros.t, 0.0)
        return zeros^
    if x2.dim(-1) != c1:
        raise Error(
            "X1 and X2 must have the same number of columns. X1: ",
            c1,
            " X2: ",
            x2.dim(-1),
        )
    _on_one_device(x1, x2)
    if not grad.on_mojo() or grad.device != x1.device:
        raise Error("_cdist_backward: grad must be on X1's device")
    if not dist.on_mojo() or dist.device != x1.device:
        raise Error("_cdist_backward: cdist must be on X1's device")
    var rank = len(batch) + 2
    var out = own(
        new_tensor(_shape_of(batch, r1, c1), rank, x1.stype, x1.device)
    )
    if p == 0 or grad.numel == 0:
        fill_value(out.t, 0.0)
        return out^
    _kernel_dtype(x1, "cdist_cuda_backward")
    _same_dtype(grad, x1)
    _same_dtype(x2, x1)
    _same_dtype(dist, x1)
    if grad.numel != product * r1 * r2 or dist.numel != grad.numel:
        raise Error(
            "_cdist_backward: grad and cdist must have ",
            product * r1 * r2,
            " elements, got ",
            grad.numel,
            " and ",
            dist.numel,
        )
    var e1 = _expanded_dense(x1, batch)
    var e2 = _expanded_dense(x2, batch)
    var g = _dense(grad)
    var d = _dense(dist)
    var ctx = ctx_for(x1.device)
    var call = KernelCall("distance", "CdistBackward")
    call.arg_dtype(0, x1.dtype)
    call.int(out.t.ptr)
    call.int(g.t.ptr)
    call.int(e1.t.ptr)
    call.int(e2.t.ptr)
    call.int(d.t.ptr)
    call.f64(p)
    call.int(_bwd_norm(p))
    call.int(product)
    call.int(r1)
    call.int(r2)
    call.int(c1)
    call.int(ctx_ptr(ctx))
    call.run()
    _ = ctx
    _ = e1^
    _ = e2^
    _ = g^
    _ = d^
    return out^


# aten::_pdist_forward(Tensor self, float p=2) -> Tensor
def _pdist_forward(args: Values) raises -> Owned:
    var x = v_tensor(args[unsafe_offset=0])
    var p = v_f64(args[unsafe_offset=1])
    if not x.contig:
        raise Error("_pdist_forward requires contiguous input")
    if x.rank != 2:
        raise Error("pdist only supports 2D tensors, got: ", x.rank, "D")
    var n = x.dim(0)
    var m = x.dim(1)
    var count = n * (n - 1) // 2 if n > 1 else 0
    var shape = IndexList[MAX_RANK](1)
    shape[MAX_RANK - 1] = count
    var out = own(new_tensor(shape, 1, x.stype, x.device))
    if count == 0:
        return out^
    if m == 0:
        fill_value(out.t, 0.0)
        return out^
    _kernel_dtype(x, "pdist_cuda")
    var ctx = ctx_for(x.device)
    var call = KernelCall("distance", "PdistForward")
    call.arg_dtype(0, x.dtype)
    call.int(out.t.ptr)
    call.int(x.ptr)
    call.int(x.ptr)
    call.f64(p)
    call.int(_fwd_norm(p))
    call.int(count)
    call.int(n)
    call.int(n)
    call.int(m)
    call.int(ctx_ptr(ctx))
    call.run()
    _ = ctx
    return out^


# aten::_pdist_backward(Tensor grad, Tensor self, float p, Tensor pdist) -> Tensor
def _pdist_backward(args: Values) raises -> Owned:
    var grad = v_tensor(args[unsafe_offset=0])
    var x = v_tensor(args[unsafe_offset=1])
    var p = v_f64(args[unsafe_offset=2])
    var dist = v_tensor(args[unsafe_offset=3])
    if not x.contig:
        raise Error("_pdist_backward requires self to be contiguous")
    if not dist.contig:
        raise Error("_pdist_backward requires pdist to be contiguous")
    if x.rank != 2:
        raise Error("pdist only supports 2D tensors, got: ", x.rank, "D")
    # empty_like(self, LEGACY_CONTIGUOUS_MEMORY_FORMAT)
    var out = own(new_tensor(x.shape, x.rank, x.stype, x.device))
    if p == 0 or grad.numel == 0 or x.numel == 0:
        fill_value(out.t, 0.0)
        return out^
    var n = x.dim(0)
    var m = x.dim(1)
    _kernel_dtype(x, "pdist_cuda_backward")
    _same_dtype(grad, x)
    _same_dtype(dist, x)
    if not grad.on_mojo() or grad.device != x.device:
        raise Error("_pdist_backward: grad must be on self's device")
    if not dist.on_mojo() or dist.device != x.device:
        raise Error("_pdist_backward: pdist must be on self's device")
    var combs = n * (n - 1) // 2
    if grad.rank != 1 or grad.dim(0) != combs or dist.numel != combs:
        raise Error(
            "_pdist_backward: grad and pdist must hold the ",
            combs,
            " pairwise distances",
        )
    var ctx = ctx_for(x.device)
    var call = KernelCall("distance", "PdistBackward")
    call.arg_dtype(0, x.dtype)
    call.int(out.t.ptr)
    call.int(grad.ptr)
    call.int(x.ptr)
    call.int(dist.ptr)
    call.f64(p)
    call.int(_bwd_norm(p))
    call.int(grad.stride(0))
    call.int(n)
    call.int(m)
    call.int(ctx_ptr(ctx))
    call.run()
    _ = ctx
    return out^


def store_autogen_out(var out: T, result: T) raises -> T:
    """An autogenerated `.out` overload (torchgen's composite: the
    functional op, `resize_output(out, result.sizes())`, `out.copy_(result)`),
    which needs a kernel here because this backend has no `aten::resize_`.
    `out` resized and filled, converted to its own dtype."""
    if not out.on_mojo() or out.device != result.device:
        raise Error(
            "Expected out tensor to have device ",
            device_str(result),
            ", but got ",
            device_str(out),
            " instead",
        )
    assert_no_internal_overlap(out)
    resize_out(out, result.shape, result.rank)
    if out.stype == result.stype:
        copy_strided_into(out, result)
    else:
        var cast = own(cast_to(result, out.stype))
        copy_strided_into(out, cast.t)
        _ = cast^  # alive past the copy
    return out^


def _ret_out(rets: Values, out_value: Value, var result: Owned) raises:
    var out = store_autogen_out(v_tensor(out_value), result.t)
    _ = result^  # alive past the copy
    ret_ref(rets, 0, out)


# aten::_cdist_forward(Tensor x1, Tensor x2, float p, int? compute_mode) -> Tensor
def op_cdist_forward(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    var r = _cdist_forward(args)
    ret_owned(rets, 0, r)


# aten::_cdist_forward.out(Tensor x1, Tensor x2, float p, int? compute_mode, *, Tensor(a!) out) -> Tensor(a!)
def op_cdist_forward_out(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    _ret_out(rets, args[unsafe_offset=4], _cdist_forward(args))


# aten::_cdist_backward(Tensor grad, Tensor x1, Tensor x2, float p, Tensor cdist) -> Tensor
def op_cdist_backward(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    var r = _cdist_backward(args)
    ret_owned(rets, 0, r)


# aten::_cdist_backward.out(..., *, Tensor(a!) out) -> Tensor(a!)
def op_cdist_backward_out(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    _ret_out(rets, args[unsafe_offset=5], _cdist_backward(args))


# aten::_pdist_forward(Tensor self, float p=2) -> Tensor
def op_pdist_forward(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    var r = _pdist_forward(args)
    ret_owned(rets, 0, r)


# aten::_pdist_forward.out(Tensor self, float p=2, *, Tensor(a!) out) -> Tensor(a!)
def op_pdist_forward_out(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    _ret_out(rets, args[unsafe_offset=2], _pdist_forward(args))


# aten::_pdist_backward(Tensor grad, Tensor self, float p, Tensor pdist) -> Tensor
def op_pdist_backward(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    var r = _pdist_backward(args)
    ret_owned(rets, 0, r)


# aten::_pdist_backward.out(..., *, Tensor(a!) out) -> Tensor(a!)
def op_pdist_backward_out(
    args: Values, n_args: Int, rets: Values, n_rets: Int
) raises:
    _ret_out(rets, args[unsafe_offset=4], _pdist_backward(args))


def register_distance(site: Site) raises:
    impl[op_cdist_forward, "_cdist_forward"](site)
    impl[op_cdist_forward_out, "_cdist_forward.out"](site)
    impl[op_cdist_backward, "_cdist_backward"](site)
    impl[op_cdist_backward_out, "_cdist_backward.out"](site)
    impl[op_pdist_forward, "_pdist_forward"](site)
    impl[op_pdist_forward_out, "_pdist_forward.out"](site)
    impl[op_pdist_backward, "_pdist_backward"](site)
    impl[op_pdist_backward_out, "_pdist_backward.out"](site)
