"""Generate MAX's concrete fusion registrations from one struct template.

MAX 26.5 drops parent-struct parameters when lowering ElementwiseUnaryOp and
ElementwiseUnaryMixedOp calls. Keep the maintained implementation generic,
then register concrete forwarders that the graph compiler can fuse.

Run ``uv run python scripts/generate_elementwise_ops.py`` after adding a kind
in custom_mojo_ops.elementwise or custom_mojo_ops.pointwise_binary, or pass
``--check`` to verify the checked-in files.
"""

import argparse
import ast
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "torch_mojo_backend/mojo/tmb/graph/elementwise_generated.mojo"
BINARY_OUTPUT = ROOT / "torch_mojo_backend/mojo/tmb/graph/pointwise_generated.mojo"
BINARY_HEADER = """# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# the native backend's pointwise SIMD math (tmb.kernels.common.pointwise_math).

import extensibility
from extensibility import ElementwiseBinaryOp

from tmb.kernels.common.pointwise_math import param_dtype, pointwise
"""
BINARY_TEMPLATE = """

@extensibility.register("pointwise_{kind}")
struct {name}(ElementwiseBinaryOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        width: SIMDLength,
    ](lhs: SIMD[dtype, width], rhs: SIMD[dtype, width]) -> SIMD[dtype, width]:
        return pointwise["{kind}", dtype, dtype, width](
            lhs, rhs, SIMD[dtype, width](0), SIMD[param_dtype[dtype](), 4](0)
        )
"""
HEADER = """# Generated by scripts/generate_elementwise_ops.py. Do not edit by hand.
# MAX 26.5 needs concrete structs for fusion; all implementations share
# ElementwiseOp[kind] and the native backend's SIMD math.

import extensibility
from extensibility import ElementwiseUnaryMixedOp

from .elementwise import ElementwiseOp
"""
TEMPLATE = """

@extensibility.register("elementwise_{kind}")
struct {name}(ElementwiseUnaryMixedOp):
    @staticmethod
    def elementwise[
        dtype: DType,
        out_dtype: DType,
        width: SIMDLength,
    ](x: SIMD[dtype, width]) -> SIMD[out_dtype, width]:
        comptime Op = ElementwiseOp["{kind}"]
        return Op.elementwise[dtype, out_dtype, width](x)
"""


def _kinds(function_name: str) -> tuple[str, ...]:
    """Read a public helper's kind annotation without importing the backend."""
    source = ROOT / "torch_mojo_backend/custom_mojo_ops.py"
    module = ast.parse(source.read_text())
    function = next(
        node
        for node in module.body
        if isinstance(node, ast.FunctionDef) and node.name == function_name
    )
    annotation = next(arg.annotation for arg in function.args.args if arg.arg == "kind")
    if not isinstance(annotation, ast.Subscript):
        raise ValueError(f"{function_name}.kind must have a Literal annotation")
    kinds = ast.literal_eval(annotation.slice)
    if not isinstance(kinds, tuple) or not all(isinstance(kind, str) for kind in kinds):
        raise ValueError(f"{function_name}.kind must be a Literal of strings")
    return cast(tuple[str, ...], kinds)


def _struct_name(prefix: str, kind: str) -> str:
    return prefix + "".join(part.capitalize() for part in kind.split("_"))


def render() -> str:
    return HEADER + "".join(
        TEMPLATE.format(kind=kind, name=_struct_name("Elementwise", kind))
        for kind in _kinds("elementwise")
    )


def render_binary() -> str:
    return BINARY_HEADER + "".join(
        BINARY_TEMPLATE.format(kind=kind, name=_struct_name("Pointwise", kind))
        for kind in _kinds("pointwise_binary")
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = ((OUTPUT, render()), (BINARY_OUTPUT, render_binary()))
    if args.check:
        for path, expected in outputs:
            if not path.exists() or path.read_text() != expected:
                print(
                    "Regenerate with uv run python scripts/generate_elementwise_ops.py"
                )
                return 1
    else:
        for path, expected in outputs:
            path.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
