"""Inject CSV-driven -D gates into eager kernel modules.

Two axes, both read from build defines and both defaulting to "everything":
  -D TMB_OPS=<csv>     -> only listed PyInit registrations are elaborated
  -D TMB_DTYPES=<csv>  -> only listed dtypes are instantiated in dtype loops

Idempotent per file (skips files already containing the helper marker).
"""

import re
import sys

HELPER = '''

# --- TMB variant gates (generated by tools/gate_variants.py) -----------------
from std.sys.defines import get_defined_string

comptime _TMB_OPS = get_defined_string["TMB_OPS", "all"]()
comptime _TMB_DTYPES = get_defined_string["TMB_DTYPES", "all"]()


@always_inline
def _tmb_csv_has(csv: StaticString, name: String) -> Bool:
    """Comptime-foldable membership test in a comma-separated -D define."""
    if csv == "all":
        return True
    var padded = String(",") + String(csv) + ","
    return padded.find(String(",") + name + ",") != -1


@always_inline
def _op_on[name: StaticString]() -> Bool:
    """With -D TMB_OPS=<csv>, only listed registrations are elaborated (and
    only their kernels compiled); everything else is skipped entirely."""
    comptime if _tmb_csv_has(_TMB_OPS, String(name)):
        return True
    else:
        return False


@always_inline
def _dt_on[dt: DType]() -> Bool:
    """With -D TMB_DTYPES=<csv>, only listed dtypes are instantiated."""
    comptime if _tmb_csv_has(_TMB_DTYPES, String(dt)):
        return True
    else:
        return False


# -----------------------------------------------------------------------------
'''

FOR_RE = re.compile(r"^(\s*)comptime for (\w+) in (.*)$")
REG_RE = re.compile(r"^(\s*)(?:b|builder)\.def_(?:py_c_)?function\(")


def gate_dtype_loops(lines: list[str]) -> tuple[list[str], int]:
    out: list[str] = []
    i = 0
    gated = 0
    while i < len(lines):
        line = lines[i]
        m = FOR_RE.match(line.rstrip("\n"))
        if not m:
            out.append(line)
            i += 1
            continue
        indent, var, rest = m.groups()
        header = [line]
        j = i + 1
        text = rest
        while not text.rstrip().endswith(":"):
            header.append(lines[j])
            text += lines[j]
            j += 1
        if "DType" not in text and "DTYPES" not in text:
            out.extend(header)
            i = j
            continue
        out.extend(header)
        out.append(f"{indent}    comptime if _dt_on[{var}]():\n")
        body_min = len(indent) + 1
        while j < len(lines):
            b = lines[j]
            if b.strip() == "":
                out.append(b)
                j += 1
                continue
            if len(b) - len(b.lstrip()) < body_min:
                break
            out.append("    " + b)
            j += 1
        gated += 1
        i = j
    return out, gated


def gate_registrations(lines: list[str]) -> tuple[list[str], int]:
    out: list[str] = []
    i = 0
    gated = 0
    in_pyinit = False
    while i < len(lines):
        line = lines[i]
        if line.startswith("def PyInit_"):
            in_pyinit = True
        m = REG_RE.match(line) if in_pyinit else None
        if not m:
            out.append(line)
            i += 1
            continue
        indent = m.group(1)
        stmt = [line]
        depth = line.count("(") - line.count(")")
        j = i + 1
        while depth > 0:
            stmt.append(lines[j])
            depth += lines[j].count("(") - lines[j].count(")")
            j += 1
        name = re.search(r'"([A-Za-z0-9_]+)"', "".join(stmt)).group(1)
        out.append(f'{indent}comptime if _op_on["{name}"]():\n')
        out.extend("    " + s for s in stmt)
        gated += 1
        i = j
    return out, gated


def transform(path: str) -> str:
    src = open(path).read()
    if "_tmb_csv_has" in src:
        return "already gated"
    lines = src.splitlines(keepends=True)
    lines, nloops = gate_dtype_loops(lines)
    lines, nregs = gate_registrations(lines)
    src = "".join(lines)
    anchor = src.index("\n\n", src.rindex("\nfrom ") if "\nfrom " in src else 0)
    src = src[:anchor] + HELPER + src[anchor:]
    open(path, "w").write(src)
    return f"dtype loops: {nloops}, registrations: {nregs}"


for p in sys.argv[1:]:
    print(p.rsplit("/", 1)[-1], "->", transform(p))
